### ISSUE TITLE
Could we have a loader which can open an arbritrary h5 file

### ISSUE THREAD

**Issue by markbasham** [imaluengo/ihseg_issues#9]
IE. when you use load at the moment, it assumes there is a particular entry in the path, could it open a choice dialog for any 3D volumes in the file.

**Comment by imaluengo** [comment]
The `load` button is suppose to read only workspace files created by the same tool. The `open` button can however read HDF5 files to grab the data. However, it currently tries to load '/data' from the file. Would adding a *dataset selector* (to the `open` button) be enough fix for this?

**Comment by markbasham** [comment]
yes please.

**Comment by markbasham** [comment]
Its working well by the way
